<?php
    
$errorMessage = "";
if($_POST["userID"] == null) 
{
    $errorMessage = errorMessage + "The userID was not provided in the request.";
}

if ($_POST["type"] == null)
{
    $errorMessage = errorMEssage + " The type of the region was not provided in the request.";
}

if ($_POST["name"] == null)
{
    $errorMessage = errorMessage + " The name of the region was not provided in the request.";
}

if ($_POST["description"] == null)
{
    $errorMessage = errorMessage + " The description of the region was not provided in the request.";
}

if ($_POST["regionID"] == null)
{
    $errorMessage = errorMessage + " The regionID of the region was not provided in the request.";
}

if ($_POST['polygonPath'] == null)
{
	$errorMessage = errorMessage + " the polygon path was not provided in the request.";
}


if ($errorMessage != "")
{
	echo "Failed with the following errors. " + $errorMessage;
	return;
}


$dsn = "mysql:host=lovett.usask.ca;dbname=cmpt350_ral362";
$username = "cmpt350_ral362";
$password = "zm6uafeyio";


try {
    $db = new PDO($dsn, $username, $password, array(PDO::ATTR_EMULATE_PREPARES => false, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION)); 
	//http://php.net/manual/en/function.json-decode.php
	$polygonPath = json_decode($_POST['polygonPath'], true);

	
	if ($polygonPath == null)
	{
		echo "The polygonPath failed to be decoded.";
	}
	else
	{
		//NOTE:: UNCOMMENTING THIS WILL DISPLAY THE JSON ID, HOWEVER IT WILL CAUSE WEIRD ERRORS WITH THE PROJECT. IT WILL CAUSE THE REGIONID TO NOT BE RETURNED
		//AND IT WILL CAUSE UNEXPECTED END OF FILES, OR UNEXPECTED TOKEN ERRORS.
		//var_dump($polygonPath);
	}
	
	//Find the new RegionID for this region.
	$statement = $db->prepare(
    "SELECT 
    reg_identifier 
    FROM 
    t_regions
	ORDER BY
	reg_identifier DESC
	LIMIT 1
    ;");
    
    $statement->execute();
    $result = $statement->fetchAll();
	
	//there should be only one
	 foreach ($result as $row) {

	 //update the regionID to be the latest one plus one.
		$regionID = $row['reg_identifier'] + 1;
	 }
		
	//Insert the region into the region table.
    $statement = $db->prepare(
    "INSERT INTO t_regions(reg_identifier, reg_user_email, reg_name, reg_description, reg_type)
    VALUES(
    :regionID,
    :userID,
    :name,
    :description,
    :type);"
    );
    $statement->bindParam(':regionID', $regionID, PDO::PARAM_INT);
    $statement->bindParam(':userID', $_POST['userID'], PDO::PARAM_STR);
    $statement->bindParam(':name', $_POST['name'], PDO::PARAM_STR);
    $statement->bindParam(':description', $_POST['description'], PDO::PARAM_STR);
    $statement->bindPAram(':type', $_POST['type'], PDO::PARAM_STR);
    $statement->execute();
    
	//Insert all of the coordinates into the region_coordinates table.
	$statement = $db->prepare(
	"INSERT INTO t_region_coordinates(reg_identifier, reg_latitude, reg_longitude)
		VALUES(
			:regionID,
			:regionLatitude,
			:regionLongitude);");
			
	//$coordinate["k"] is the latitude, and $coordinate["D"] is the longitude. These names are generated by using the JSON.stringify() method in saveRegionToDB method in googlemaps_api_extension.js
	foreach($polygonPath as $coordinate)
	{
		$statement->bindParam(':regionID', $regionID, PDO::PARAM_INT);
		$statement->bindParam(':regionLatitude', $coordinate["k"], PDO::PARAM_STR);
		$statement->bindParam(':regionLongitude', $coordinate["D"], PDO::PARAM_STR);
		$statement->execute();
	}
	
	echo $regionID;

}

 catch (PDOException $e) {
    $errorResponse = array("error" => $e->getMessage());
    echo json_encode($errorResponse);
}


?>
